# Generated by Django 2.0.8 on 2018-09-29 07:56

import WebAdminRadio.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('tabla', models.CharField(max_length=20)),
                ('data_nueva', models.CharField(max_length=50)),
                ('data_actual', models.CharField(max_length=50)),
                ('fecha_creado', models.DateTimeField()),
                ('fecha_modificado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concursante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premios', models.CharField(max_length=500)),
                ('ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Concursante')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Emisora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('frecuencia_dial', models.CharField(max_length=8)),
                ('url_streaming', models.CharField(max_length=150)),
                ('sitio_web', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=500)),
                ('ciudad', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('logotipo', models.ImageField(upload_to=WebAdminRadio.models.emisora_file_location)),
                ('activo', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('activo', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.DateTimeField()),
                ('tipo', models.CharField(max_length=1)),
                ('dia_semana', models.CharField(blank=True, max_length=9, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('nro_dias', models.IntegerField()),
                ('activo', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='frecuencia_publicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFrecuencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Frecuencia')),
            ],
        ),
        migrations.CreateModel(
            name='HiloChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=9)),
                ('idEmisora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Emisora')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=9)),
                ('fecha_inicio', models.TimeField()),
                ('fecha_fin', models.TimeField()),
                ('activo', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=500)),
                ('idHiloChat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.HiloChat')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=1)),
                ('respuesta_c', models.CharField(max_length=150)),
                ('idConcurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Concurso')),
            ],
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('cliente', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=350)),
                ('url', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=1)),
                ('imagen', models.ImageField(blank=None, upload_to=WebAdminRadio.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='RedSocial_emisora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('link', models.CharField(max_length=50)),
                ('idEmisora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Emisora')),
            ],
        ),
        migrations.CreateModel(
            name='RedSocial_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=150)),
                ('correcta', models.CharField(max_length=1)),
                ('idConcursante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Concursante')),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('slogan', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=250)),
                ('imagen', models.ImageField(upload_to=WebAdminRadio.models.segmento_file_location)),
                ('activo', models.CharField(default='A', max_length=1)),
                ('idEmisora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Emisora')),
            ],
        ),
        migrations.CreateModel(
            name='segmento_horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Horario')),
                ('idSegmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Segmento')),
            ],
        ),
        migrations.CreateModel(
            name='segmento_publicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPublicidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Publicidad')),
                ('idSegmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Segmento')),
            ],
        ),
        migrations.CreateModel(
            name='segmento_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSegmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Segmento')),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.CharField(max_length=250)),
                ('activo', models.CharField(default='A', max_length=1)),
                ('idEmisora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Emisora')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono_emisora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_telefono', models.CharField(max_length=10)),
                ('idEmisora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Emisora')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_sugerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nac', models.DateField()),
                ('imagen', models.ImageField(blank=True, upload_to=WebAdminRadio.models.upload_location)),
                ('rol', models.CharField(max_length=1)),
                ('activo', models.CharField(default='A', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='telefono_usuario',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Usuario'),
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='idTipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Tipo_sugerencia'),
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Usuario'),
        ),
        migrations.AddField(
            model_name='segmento_usuario',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Usuario'),
        ),
        migrations.AddField(
            model_name='redsocial_usuario',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Usuario'),
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Usuario'),
        ),
        migrations.AddField(
            model_name='frecuencia_publicidad',
            name='idSegmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Segmento'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='idPublicidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Publicidad'),
        ),
        migrations.AddField(
            model_name='concurso',
            name='idEncuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Encuesta'),
        ),
        migrations.AddField(
            model_name='concursante',
            name='idUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebAdminRadio.Usuario'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='idPregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Pregunta'),
        ),
    ]
