# Generated by Django 2.1.1 on 2018-10-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmento',
            name='slug',
        ),
    ]
