# Generated by Django 2.0.8 on 2018-09-27 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emisora',
            old_name='nomnbre',
            new_name='nombre',
        ),
    ]
