# Generated by Django 2.1.1 on 2018-10-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0002_remove_segmento_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emisora',
            name='nombre',
        ),
        migrations.AddField(
            model_name='segmento',
            name='slug',
            field=models.SlugField(default='segmento', unique=True),
            preserve_default=False,
        ),
    ]
