# Generated by Django 2.1.1 on 2019-01-03 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0003_auto_20181129_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencia',
            name='idSegmento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Segmento'),
        ),
        migrations.AlterField(
            model_name='emisora',
            name='sitio_web',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
