# Generated by Django 2.0.8 on 2018-09-27 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0003_auto_20180927_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segmento',
            old_name='idEmsiora',
            new_name='idEmisora',
        ),
    ]
