# Generated by Django 2.0.8 on 2018-12-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0003_auto_20181124_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencia',
            name='idSegmento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Segmento'),
        ),
    ]
