# Generated by Django 2.1.1 on 2018-10-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0003_auto_20181003_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emisora',
            name='slug',
        ),
    ]
