# Generated by Django 2.0.8 on 2018-09-27 05:54

import WebAdminRadio.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0004_auto_20180927_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisora',
            name='logotipo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=WebAdminRadio.models.emisora_file_location),
            preserve_default=False,
        ),
    ]
