# Generated by Django 2.0.8 on 2018-12-07 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0004_sugerencia_idsegmento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerencia',
            name='idSegmento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Segmento'),
        ),
    ]
