# Generated by Django 2.1.1 on 2019-01-17 13:30

import WebAdminRadio.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0004_auto_20190103_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=350)),
                ('url', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to=WebAdminRadio.models.upload_location_image)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Frecuencia')),
            ],
        ),
    ]
