# Generated by Django 2.1.1 on 2019-01-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0005_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Segmento'),
        ),
    ]
