# Generated by Django 2.1.1 on 2018-09-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0005_emisora_logotipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='concursante',
            name='activo',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='emisora',
            name='activo',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='activo',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='frecuencia',
            name='activo',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='horario',
            name='activo',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='segmento',
            name='activo',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='activo',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
