# Generated by Django 2.1.1 on 2018-10-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0006_auto_20181003_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emisora',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='segmento',
            name='slug',
        ),
    ]
