# Generated by Django 2.1.1 on 2018-10-03 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0007_auto_20181003_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisora',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segmento',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
