# Generated by Django 2.1.1 on 2019-01-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0007_auto_20190117_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='url',
        ),
    ]
