# Generated by Django 2.1.1 on 2019-01-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0008_remove_imagenes_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenes',
            old_name='imagen',
            new_name='url',
        ),
    ]
