# Generated by Django 2.0.8 on 2018-10-04 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0009_remove_usuario_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='dia',
        ),
    ]
