# Generated by Django 2.1.1 on 2019-01-17 15:19

import WebAdminRadio.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0009_auto_20190117_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=350)),
                ('url', models.FileField(upload_to=WebAdminRadio.models.upload_location_video)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.Segmento')),
            ],
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='idConcurso',
            new_name='idEncuesta',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='idEmisora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Emisora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='idSegmento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='WebAdminRadio.Segmento'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta_c',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
