# Generated by Django 2.0.8 on 2018-10-04 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0010_remove_horario_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='dia',
            field=models.CharField(default=django.utils.timezone.now, max_length=9),
            preserve_default=False,
        ),
    ]
