# Generated by Django 2.1.1 on 2018-10-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0011_horario_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='dia',
        ),
    ]
